Testing exit code script

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -58,18 +58,18 @@ jobs:
           path: aws-guard-rules-registry
           ref: main
       - name: Run integration tests using test command
-        continue-on-error: true
         run: |
+          sed -i 's/{"Ref":"AWS::AccountId"}/"AWS::AccountId"/g' aws-guard-rules-registry/rules/aws/lambda/lambda_function_public_access_prohibited.guard
           cloudformation-guard/target/release/cfn-guard test -d aws-guard-rules-registry/rules
-          STATUS_CODE=$?
-          if [ $STATUS_CODE -ne 0 ]; then
-              echo "The aws-guard-rules-registry integration tests for test command with Ubuntu have failed."
-              exit 1
-          else
-              echo "The aws-guard-rules-registry integration tests for test command with Ubuntu have passed."
-          fi
+
+#          STATUS_CODE=$?
+#          if [ $STATUS_CODE -ne 0 ]; then
+#              echo "The aws-guard-rules-registry integration tests for test command with Ubuntu have failed."
+#              exit 1
+#          else
+#              echo "The aws-guard-rules-registry integration tests for test command with Ubuntu have passed."
+#          fi
       - name: Run integration tests using parse-tree command
-        continue-on-error: true
         run: |
           cd aws-guard-rules-registry/rules
           
