Added powershell commands for windows

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -39,12 +39,11 @@ jobs:
       - name: Rustfmt Check
         uses: actions-rust-lang/rustfmt@v1
 
-  aws-guard-rules-registry-integration-tests:
+  aws-guard-rules-registry-integration-tests-linux:
     strategy:
       matrix:
-        os: [ ubuntu-latest, macos-latest, windows-latest ]
+        os: [ ubuntu-latest, macos-latest ]
     runs-on: ${{ matrix.os }}
-    shell: bash
     name: Integration tests against aws-guard-rules-registry
     steps:
       - uses: actions/checkout@v3
@@ -110,5 +109,68 @@ jobs:
           else
               echo "All the rules have succeeded the parse-tree integration tests."
           fi
+
+  aws-guard-rules-registry-integration-tests-windows:
+    runs-on: windows-latest
+    name: Integration tests against aws-guard-rules-registry
+    steps:
+      - uses: actions/checkout@v3
+        name: Checkout cfn-guard
+        with:
+          path: cloudformation-guard
+      - name: Build binary
+        run: |
+          cd cloudformation-guard/guard/
+          cargo build --release
+      - uses: actions/checkout@v3
+        name: Checkout aws-guard-rules-registry
+        with:
+          repository: aws-cloudformation/aws-guard-rules-registry
+          path: aws-guard-rules-registry
+          ref: main
+      - name: Run integration tests using test command
+        run: |
+          if (cloudformation-guard/target/release/cfn-guard test -d aws-guard-rules-registry/rules) {
+              echo "The integration tests for test command have passed."
+          }
+          else {
+              echo "The integration tests for test command have failed."
+              exit 1
+          }
+
+      - name: Run integration tests using parse-tree command
+        run: |
+          cd aws-guard-rules-registry/rules
           
+          $FAILED_RULES = @()
+          $SKIPPED_RULES = @()
           
+          $rules  = @(Get-ChildItem -Path .\ -Filter *.guard -Recurse -File)
+
+          Foreach ($rule in $rules) {
+              $rule_files_without_comments = (Get-Content $rule.FullName) -replace '^[ \s]*#.*$', ''
+              if ([String]::IsNullOrWhiteSpace($rule_files_without_comments)){
+              $SKIPPED_RULES += "$rule"
+          }
+          elseif (../../cloudformation-guard/target/release/cfn-guard parse-tree --rules $rule.FullName) {
+              continue
+          } else {
+              $FAILED_RULES += "$rule"
+            }
+          }
+          
+          $SKIPPED_RULE_COUNT = $SKIPPED_RULES.Length
+          if ($SKIPPED_RULE_COUNT -gt 0) {
+              echo "The following `$SKIPPED_RULE_COUNT.Length` rule(s) were skipped because they contained only comments:"
+              echo $SKIPPED_RULES
+          }
+          
+          $FAILED_RULE_COUNT = $FAILED_RULES.Length
+  
+          if ($FAILED_RULE_COUNT -gt 0) {
+              echo "The following $FAILED_RULE_COUNT rule(s) have failed the parse-tree integration tests with a non-zero error code:"
+              echo $FAILED_RULES
+              exit 1
+          } else {
+              echo "All the rules have succeeded the parse-tree integration tests."
+          }
